server:
  port: 8080
spring:
  datasource:
    username: root
    password: a123456
    url: jdbc:mysql://localhost:3307/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity.springboot
spring-to-boot:
  sync-day-before: -7
  sync-day-before-desc: 7
  token-expire-hour: 12
logging:
  level:
    com.example.springboot.mapper: debug